apiVersion: apps/v1
kind: Deployment
metadata:
name: demo-web
spec:
replicas: 2
selector:
matchLabels:
app: demo-web
template:
metadata:
labels:
app: demo-web
spec:
containers:
- name: demo-web
image: chigullanaveen/demo-web:latest
ports:
- containerPort: 80
-------------------

apiVersion: v1
kind: Service
metadata:
name: demo-web-svc
spec:
type: LoadBalancer
selector:
app: demo-web
ports:
- port: 80
targetPort: 80
